### ISSUE TITLE
from cython.operator cimport dereference as deref

### ISSUE THREAD

**Issue by WYM1234** [FFrankyy/FINDER#26]
Appearing one error "Unresolved reference 'dereference'" when I open this project using pycharm(Windows 10)

**Comment by WYM1234** [comment]
Solved

**Comment by Shang04** [comment]
I‘m now stumped by the same problem now. How did you resolved it?

**Comment by Shang04** [comment]
I‘m now stumped by the same problem. How did you resolved it?

**Comment by Shang04** [comment]
I‘m now stumped by the same problem. How did you resolve it?
