### ISSUE TITLE
Additions to ReadME for Windows Users

### ISSUE THREAD

**Issue by FL33TW00D** [FFrankyy/FINDER#5]
For anyone else trying to install on Windows 10:
1. You must have CUDA 10.0 ToolKit installed, can be found [here.](https://developer.nvidia.com/cuda-10.0-download-archive)
2. You need to copy the cudnn64_7.dll downloaded from [here.](https://developer.nvidia.com/rdp/cudnn-download)
3. The command to run the Synthetic Tests is as follows: set CUDA_VISIBLE_DEVICES=-1 & python testSynthetic.py

**Comment by fanchangjun** [comment]
Thanks.
