### ISSUE TITLE
Failure with no error message

### ISSUE THREAD

**Issue by FL33TW00D** [FFrankyy/FINDER#6]
Hi there,
I have been using FINDER, and it works great on the 9 provided real datasets. It also works well on a Watts-Strogatz graph generated by networkX.
I am attempting to use it on some bespoke data. I have ensured that the graph is all one connected component using NetworkX, and it looks like the provided image:
![image](https://user-images.githubusercontent.com/45471420/86907561-23591e00-c10d-11ea-9889-31ec7ac86a11.png)

I will also provide the TXT file.

Upon running this, the code simply pauses and then ends, like so:
![image](https://user-images.githubusercontent.com/45471420/86907619-3b30a200-c10d-11ea-9c7c-e240145a2f24.png)

Any ideas would be appreciated.
[data.txt](https://github.com/FFrankyy/FINDER/files/4890084/data.txt)

**Comment by fanchangjun** [comment]
Please ensure the network be a connected component, no self-loops, no isolated nodes, no multiple edges between the same pair of nodes.

**Comment by FL33TW00D** [comment]
> 
> 
> Please ensure the network be a connected component, no self-loops, no isolated nodes, no multiple edges between the same pair of nodes.

Hi there,
Thank you for the response.
I have now a single connected component, no self loops and no isolated nodes. It is construced using a NetworkX graph which does not allow multiple edges.
![image](https://user-images.githubusercontent.com/45471420/86944866-40f3ab00-c140-11ea-920c-114048dd1e31.png)
[datav2.txt](https://github.com/FFrankyy/FINDER/files/4891941/datav2.txt)


Any more ideas? Would really help me out.

Many Thanks,
Chris

**Comment by FL33TW00D** [comment]
Fixed.
Was a mistake in the construction of my adjacency matrix.
Thank you for your help @FFrankyy
