### ISSUE TITLE
Key error with Critical Node Cost problem

### ISSUE THREAD

**Issue by FL33TW00D** [FFrankyy/FINDER#7]
Hi there,
I am getting a KeyError when attempting to run your example datasets (such as Crime) with the provided .gml cost data.

I redownloaded and rebuilt a new version of FINDER from your repo, but I am still seeing the key error. Please find the error log below.

![image](https://user-images.githubusercontent.com/45471420/86933219-36cab000-c132-11ea-877b-348094b62f94.png)

Do you know what is causing this?

Many Thanks,
Chris

**Comment by fanchangjun** [comment]
In 'weights.append(g.node[i]['weight'])' , please change "g.node[str(i)]" under the weighted scenario.

**Comment by FL33TW00D** [comment]
> 
> 
> In 'weights.append(g.node[i]['weight'])' , please change "g.node[str(i)]" under the weighted scenario.

Thank you very much it works.

**Comment by xiaohu-art** [comment]
![屏幕截图 2022-07-16 093057](https://user-images.githubusercontent.com/84264941/179329401-a65a3bff-f519-411d-9034-f5d465f2c6b9.png)
hi there !
I have modified the error mentioned above, but it still doesn't work.
what's wrong here please?

**Comment by Stephaniesuu** [comment]
> ![屏幕截图 2022-07-16 093057](https://user-images.githubusercontent.com/84264941/179329401-a65a3bff-f519-411d-9034-f5d465f2c6b9.png) 你好呀 ！ 我修改了上面提到的错误，还是不行。 请问这里有什么问题吗？

hello， I'm having the same problem, could you help me？
