### ISSUE TITLE
Modifying Connectivity Measures

### ISSUE THREAD

**Issue by MSK0306** [FFrankyy/FINDER#9]
Hello,
In the article authors claim that in principle algorithm can work with any properly defined connectivity measure. I examined supplementary information document however, I could not find a description of how to change connectivity measures. Is this modification too complex to be described? If not how can I do that?
Thank you.

**Comment by fanchangjun** [comment]
Our reward is defined basing on the graph connectivity, thus the changing the reward means to change the connectivity measures.
